### ISSUE TITLE
Import bottle

### ISSUE THREAD

**Issue by davemenkehorst** [CrossGridder/CrossGridder_1.2#3]
I'm feeling so dumb. I cannot import the bottle.
Codewavers site says:
Step 4 - A dropdown window appears, select the location where the archive was saved.
Step 5 - Locate the .cxarchive and select it.

There is no .cxachrive in the ZIP file CrossGridder_1.2

Using Crossover Versie 21.1 (21.1.0.33869)

**Comment by davemenkehorst** [comment]
Okay So unpacking it with The Unarchiver did the trick

**Comment by CrossGridder** [comment]
Hi Dave, thanks for trying CrossGridder. Yes, Keka or The Unarchiver must be used. The default macOS utility decompresses also the bottle itself and it creates the c drive, right? 

However, closing as solved, thanks!
