### ISSUE TITLE
Cannot install any setups

### ISSUE THREAD

**Issue by davemenkehorst** [CrossGridder/CrossGridder_1.2#4]
So when i try to install a setup file, it always fails with a Runtime error
Cannot import DLL [path to] ISSKINU.DLL

When i try to use the included Innoextractor. 
Innoextractor fails with unable to create directory when i try to extract te EXE file. (i cannot change the path to extract)
Also if i open the exe installer from the bottles desktop

**Comment by CrossGridder** [comment]
Please, don't open issues, open discussions and if it the case I will open an issue
